Рефакторинг существующего кода
frontend-park-mail-ru/2023_1_MRGA pull request #5
Opened 2023-04-07 14:41 UTC by Yakwilik

2023-04-09 20:38 UTC, wd055 commented on public/lib/jsx/index.js
> +    // if (!nextNode) {
Нужны ли тут эти комменты. Стоит или удалить, или добавить пояснение, почему это пока закомментировано

2023-04-09 20:38 UTC, wd055 commented on public/lib/jsx/index.js
> +    vRoot = virtualRoot;
Пустая строка. Опять же в линтер стоит добавить

2023-04-09 20:38 UTC, wd055 commented on public/api/api.js
>  import {Ajax} from "./ajax.js";
По идее это всё папки не public, а src

2023-04-09 20:38 UTC, wd055 commented on public/api/api.js
>  import {Ajax} from "./ajax.js";
Public это больше про шрифты, картинки, html

2023-04-09 20:38 UTC, wd055 commented on public/lib/jsx/components/link/link.js
> +export const Link = ({href, ...props}, children) => {
Это по идее не lib, а компонент. Спорная тема

2023-04-09 20:38 UTC, wd055 commented on public/router/router.js
> +    // {path:'/', component}
Зачем этот коммент

2023-04-09 20:38 UTC, wd055 commented on public/router/router.js
> +    console.log("popstate");
консоль стоит удалить или добавить проверку на дев окружение. Так же консоль стоит добавить в линтер

2023-04-09 20:38 UTC, wd055 commented on public/components/UI/forms/form/form.js
> +
пустая строка лишняя)

2023-04-09 20:38 UTC, wd055 commented on public/components/UI/forms/form/form.js
> +}
А тут не хватает пустой строки)

2023-04-09 20:38 UTC, wd055 commented on public/components/App/registrationForm/registrationForm.js
> +                    // ref={login}
Коммент

2023-04-09 20:38 UTC, wd055 commented on public/lib/redux/index.js
> +export const createStore = (rootReducer, initialState) => {
Почему redux, а не store?

2023-04-09 20:38 UTC, wd055 commented on public/components/App/authorizationForm/authorizationForm.js
> +        // Navigate({to: "/"});
коммент

2023-04-09 20:38 UTC, wd055 commented on public/components/App/authorizationForm/authorizationForm.js
> +        console.log(password.getValue().value);
логи

2023-04-09 20:38 UTC, wd055 commented on public/components/App/header/header.js
> +    </HeaderContainer>)
) на новую строку

2023-04-09 20:38 UTC, wd055 commented on public/components/App/authorizationForm/authorizationForm.js
> +    return (
Нет пустой строки

2023-04-09 20:38 UTC, wd055 commented on public/components/App/pages/authorization/authorization.js
> +    return (<>
lint

2023-04-09 20:38 UTC, wd055 commented on public/ts.ts
> +let x: Number = 5;
Что это?

2023-04-09 20:56 UTC, wd055 requested changes

2023-04-09 20:56 UTC, wd055 commented on public/components/App/authorizationForm/authorizationForm.js
> +import styles from "components/App/authorizationForm/authorizationForm.module.css";
Может можно сократить до "./authorizationForm.module.css"?

2023-04-09 20:56 UTC, wd055 commented on public/components/App/authorizationForm/authorizationForm.module.css
> +.inviteText p{
почему класс сразу не на параграфе, а на его родителе?

2023-04-09 20:56 UTC, wd055 commented on public/components/App/header/header.module.css
> +.headerElement {
Не по БЭМу, должен быть просто header

2023-04-09 20:56 UTC, wd055 commented on public/components/App/pages/lenta/feed.js
> +        <div className={"container"}>
Стили не по БЭМу

2023-05-05 14:44 UTC, Yakwilik commented on .gitignore
> +stats.json
добавил

2023-05-05 14:45 UTC, Yakwilik commented on public/api/api.js
> +    : 'http://5.159.100.59:8080';
nginx только на фронте, у апи два пути, /meetme для авторизованных запросов и /api для публичных, поэтому так

2023-05-05 14:46 UTC, Yakwilik commented on public/api/api.js
> +const ApiUrl = BackendHost + "/meetme/";
выше написал, почему так

2023-05-05 14:47 UTC, Yakwilik commented on public/lib/jsx/utils.js
> +}
ок

2023-05-05 14:47 UTC, Yakwilik commented on package.json
> +    "stats": "webpack --json > stats.json && webpack-bundle-analyzer stats.json"
добавил todo

2023-06-01 09:47 UTC, merged