Fix bugs with chats list
frontend-park-mail-ru/2023_1_MRGA pull request #9
Opened 2023-05-07 17:28 UTC by masharpik

2023-05-07 17:51 UTC, wd055 requested changes

2023-05-07 17:51 UTC, wd055 commented on src/components/App/pages/chat/chatWidget/chatList/chatList.js
> +        ws.addEventListener("message", (event) => {
Это должно быть отдельно от верстки в отдельном "контроллере"

2023-05-07 17:51 UTC, wd055 commented on src/lib/jsx/utils.js
> +    return `${day}.${month}.${year.slice(-2)} ${hours}:${minutes}`;
В идеале дату и год показывать не всегда, только если дата и/или год другой. Чтобы визуального мусора меньше было

2023-05-07 17:59 UTC, masharpik commented on src/components/App/pages/chat/chatWidget/chatList/chatList.js
> +        ws.addEventListener("message", (event) => {
Не могу никак... Данные на страницы для перерисовки на этой странице. Посмотри нашу реализацию.

2023-05-10 11:30 UTC, wd055 requested changes

2023-05-10 11:30 UTC, wd055 commented on src/api/ws_chat_api.js
> +    // static send(sentAt, chatId, userIds, msg) {
Почему это закомментировано? Стоит или удалить, или добавить комментарий, типа TODO ...

2023-05-10 11:33 UTC, wd055 approved these changes

2023-05-10 11:34 UTC, merged